version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2-jdk
    steps:
      - run: |
          ls
          pwd
          ls ~/project
          ls ~/code
          ./gradlew test




